### PR TITLE
fix for 2024.4

### LINKED ISSUE #130: Broken on HA 2024.4.0b0
**Environment**
- Home Assistant Core release with the issue: 2024.4.0b0
- This custom component release with the issue: 1.5.5
- Last working this custom component release (if known): n/a
- Operating environment (Home Assistant/Supervisor/Docker/venv): HA OS

**Describe the bug**
After updating HA to 2023.4 the integration does not load anymore.

**Steps to Reproduce**
Update to HA core April beta release.

**Expected behavior**
Integration still works.

**Debug log**
```text
Logger: homeassistant.config
Source: config.py:1437
First occurred: 20:50:40 (1 occurrences)
Last logged: 20:50:40

Platform error: binary_sensor - cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1437, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1072, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1147, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1135, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1062, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1235, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1265, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/car_wash/binary_sensor.py", line 18, in <module>
    from homeassistant.components.weather import (
ImportError: cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
```

### PR DESCRIPTION
**Pull request by Fischelsberger**
## Proposed change
Replacing the old "Forecast" Attribut with a service call of "weather.get_forecasts" so that it's working with 2024.4.
Tested it with Homeassistant 2024.3 and 2024.4, working with booth.

Also fixed an issue wich was within that line.
`datetime.utcfromtimestamp(fc_date / 1000)`
Some Extension provided by Homeassistant devcontainer or python itself requested that change...

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an this integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #130 #128 
- This PR is related to issue:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] The code has been formatted using Black (`black --fast custom_components`)

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated to README.md

### CODE REVIEW

File: custom_components/car_wash/binary_sensor.py [hunk 1]
```diff
@@ -157,7 +158,15 @@ async def async_update(self):
         tmpu = self.hass.config.units.temperature_unit
         temp = wdata.attributes.get(ATTR_WEATHER_TEMPERATURE)
         cond = wdata.state
-        forecast = wdata.attributes.get(ATTR_FORECAST)
+
+        daily_response = await self.hass.services.async_call(
+            "weather",
```
Comment (golles) [inline custom_components/car_wash/binary_sensor.py]: You might want to use `DOMAIN` from https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/const.py#L50

File: custom_components/car_wash/binary_sensor.py [hunk 2]
```diff
@@ -157,7 +158,15 @@ async def async_update(self):
...
+            "get_forecasts",
```
Comment (golles) [inline custom_components/car_wash/binary_sensor.py]: You might want to use `SERVICE_GET_FORECASTS` from https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/__init__.py#L137

**Review by golles — APPROVED** [review]
LGTM

**Comment by Fischelsberger** [comment]
@golles, I've implemented your suggestions, but only tested it with 2024.4 this time.
Also im very new to the git-game, so not sure if "force push" in the old commit was the best choice...

**Comment by sudoxreboot** [comment]
Implemented your changes. Am now getting binary result. Can't tell if it's working though, is 'Off" Wash or Don't Wash?

**Comment by Fischelsberger** [comment]
tbh, i'm 99% sure that it always was binary.
But now as I think about, the "translation" don't make any sense with just binary results?

off = don't wash
on = wash

**Comment by sudoxreboot** [comment]
It's working. Thank you. I believe it used to say "wash" and "don't_wash". But knowing which is which is good. Apparently it's gonna snow tomorrow, it's sunny today so I was like "why not wash?" Now I know. Thanks for the fix!

**Review by golles — APPROVED** [review]
@Fischelsberger thanks for addressing the comment. This looks good and I've also tested it locally and no issues!

I'm not the owner of this repo so I don't know what @Limych would require. Hopefully, he can have a look at this and also approve the usage of the workflows in this PR so we can see if CI passes.

**Comment by Fischelsberger** [comment]
> @Fischelsberger thanks for addressing the comment. This looks good and I've also tested it locally and no issues!
> 
> I'm not the owner of this repo so I don't know what @Limych would require. Hopefully, he can have a look at this and also approve the usage of the workflows in this PR so we can see if CI passes.

@golles Wait, is this fixing your #128 then aswell?

**Comment by golles** [comment]
> > @Fischelsberger thanks for addressing the comment. This looks good and I've also tested it locally and no issues!
> > I'm not the owner of this repo so I don't know what @Limych would require. Hopefully, he can have a look at this and also approve the usage of the workflows in this PR so we can see if CI passes.
> 
> @golles Wait, is this fixing your #128 then aswell?

Yes indeed, it's basically the same issue

File: custom_components/car_wash/binary_sensor.py [hunk 3]
```diff
@@ -185,7 +197,7 @@ async def async_update(self):
             fc_date = fcast.get(ATTR_FORECAST_TIME)
             if isinstance(fc_date, int):
                 fc_date = dt_util.as_local(
-                    datetime.utcfromtimestamp(fc_date / 1000)
+                    datetime.datetime.fromtimestamp(fc_date, tz=datetime.timezone.utc)
```
Comment (Limych) [inline custom_components/car_wash/binary_sensor.py]: What are these changes for?  What problem do they solve?

File: custom_components/car_wash/binary_sensor.py [hunk 4]
```diff
@@ -157,7 +161,15 @@ async def async_update(self):
...
-        forecast = wdata.attributes.get(ATTR_FORECAST)
+
+        daily_response = await self.hass.services.async_call(
+            WEATHER_DOMAIN,
+            SERVICE_GET_FORECASTS,
+            {"entity_id": self._weather_entity, "type": "daily"},
+            blocking=True,
+            return_response=True,
+        )
+        forecast = daily_response[self._weather_entity]["forecast"]
```
Comment (Limych) [inline custom_components/car_wash/binary_sensor.py]: Please add a check for the presence of a result in the return value (daily_response).  And also add a unit test for your code.

**Review by Limych — CHANGES_REQUESTED** [review]

File: custom_components/car_wash/binary_sensor.py (hunk 3 above)
Comment (Fischelsberger) [reply custom_components/car_wash/binary_sensor.py]: No Problem, but was "request" via vscode Extension probably.
Documentation: https://docs.python.org/3/library/datetime.html#datetime.datetime.utcfromtimestamp

Deprecated since version 3.12: Use [datetime.fromtimestamp()](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) with [UTC](https://docs.python.org/3/library/datetime.html#datetime.UTC) instead.

Comment (Limych) [reply custom_components/car_wash/binary_sensor.py]: Ok. Thanks

File: custom_components/car_wash/binary_sensor.py (hunk 4 above)
Comment (Fischelsberger) [reply custom_components/car_wash/binary_sensor.py]: Thank you for the review and requested changes.
I've just added a new commit, with the changes which are looking good to me.

Also changed some imports, because ruff suggested these changes.

File: custom_components/car_wash/binary_sensor.py [hunk 5]
```diff
@@ -157,7 +160,23 @@ async def async_update(self):
...
+        daily_response = await self.hass.services.async_call(
+            WEATHER_DOMAIN,
+            SERVICE_GET_FORECASTS,
+            {"entity_id": self._weather_entity, "type": "daily"},
+            blocking=True,
+            return_response=True,
+        )
+        if not (isinstance(daily_response, dict)):
+            self._attr_is_on = None
+            raise HomeAssistantError("daily_response is empty.")
```
Comment (Limych) [inline custom_components/car_wash/binary_sensor.py]: This error message is not clear to the user if he sees it in the log.  The user does not know what daily_response is.

File: custom_components/car_wash/binary_sensor.py [hunk 6]
```diff
@@ -157,7 +160,23 @@ async def async_update(self):
...
+        if (len(daily_response) == 0) or (
```
Comment (Limych) [inline custom_components/car_wash/binary_sensor.py]: It seems to me, or is there an error in the logic of the conditional operator?

**Review by Limych — CHANGES_REQUESTED** [review]
And please add unit tests to cover code you're made.

File: custom_components/car_wash/binary_sensor.py (hunk 6 above)
Comment (Fischelsberger) [reply custom_components/car_wash/binary_sensor.py]: oh, yeah, seems you're right!, fixed it with new commit.

File: custom_components/car_wash/binary_sensor.py (hunk 5 above)
Comment (Fischelsberger) [reply custom_components/car_wash/binary_sensor.py]: fixed it with new commit, by just using the original message
"Can't get forecast data! Are you sure it's the weather provider?"

by setting `forecast = None`

**Comment by Fischelsberger** [comment]
> And please add unit tests to cover code you're made.

Sorry @Limych, I don't really understand the whole unit test thing...
It seems to me, with the original [devcontainer.json](https://github.com/Limych/ha-car_wash/blob/dev/.devcontainer/devcontainer.json) it's no longer working.
Also the Image there [https://ghcr.io/ludeeus/devcontainer/integration:stable](https://ghcr.io/ludeeus/devcontainer/integration:stable) is Deprecated.

I've tried multiple ways, but I simply can't understand that (right now)...
I'm not a programmer myself, I just wanted to have that thing running again.
If anyone can provide me with some insights or even better, a working unit-test, I will be more then glad to implement it and run these tests and the devcontainer myself.

File: custom_components/car_wash/binary_sensor.py (hunk 5 above)
Comment (Limych) [reply custom_components/car_wash/binary_sensor.py]: The option is suitable, but it will be better if the error message is more unique, so that it is also more clear to developers about where the failure actually occurred.

**Comment by Limych** [comment]
With unit tests everything is quite simple.  We take the existing code as a basis, but we need to check all new branches according to the conditions.  It is necessary to patch self.hass.services.async_call in the test and return two variants of results - normal and error.  And check that the code reacts correctly to each option.  Tomorrow I'll try to find some time and write some sample code.

**Comment by Limych** [comment]
Closed because these changes are no longer necessary due to the release of a new version of the component.
